# DisasterTV_AI.yml
# 사전 체크 
# 1. 보도국 시스템 OS가 윈도우 인가 리눅스인가?
# 2. 비디오 입력 연동 처리
# 3. 오디오 연결 가능한가(Option)
# 4. KIT S/W 업그레이드(캡쳐화면 로딩)
# 5. 외부 인터넷 연결 필요 : 파이썬과 필요 패키지 설치
# 6. OPEN AI API필요 

# 설치 과정 
# 1. 비디오 입력 설정(USB, RTMP, 환경에 맞게 설정)
# 2. RTMP 인경우 여러 환결설정 필요
# 3. 파이썬과 패키지 설치 (visual studio code 필요한가?)
# 4. 자막인식을 위한 Tesseract 프로그램 설치 
# 5. 글꼴 파일 설치
# 6. OPEN_AI API 환경 설정
# 7. ffmpeg

# Update - 2025년 4월 10일 : 정파시간 오작동 개선 / yaml 파일정리
# # default.yml : 연구개발 테스트 운영 서버 기준으로 설정함.
# # Override.ml : 재난센터 서버 또는 코드 개발 서버 기준으로 필요시 수정함.


# 1. 카카오 채널 알림을 할지 설정함.
kakao_on: False

# 2. 입력 비디오 경로 
video_path: "rtmp://10.30.17.108:1935/live/kbs" # 정상 화면 크기 : 960 X 540
ffmpeg_enable: 1  #오디오 재생을 위해 ffmpeg설치했을때 1

# 3. CAP 수신 파일 경로 
path_cap: "C:/CGMS/file/cap/"

# CAP_process_mandatory_only ( 디버거 모드에서 = Flase,  )
CAP_process_mandatory_only : False

# 4. 파일 경로 : 방송 화면 캡쳐 파일 저장할 경로
path_capture: "C:/CGMS/captures"  # 재난방송온라인 수신S/W에 표출할 이미지 전달
path_capture2: "./captures"       # 자체 디버깅용으로 보관관
 

#캡쳐파일 최대 저장 기간(일)
capture_stay : 8    

# 긴급 재난코드
emergency_event_code :  {'FEW', 'EQW', 'EQI', 'EEW', 'CPW', 'CNW', 'CDC', 'CCW', 'CAW'}

# 긴급 재난 유형별 송출 시간 :
# 지진은        10회 반복 / 표출 시간 30분 
# 민방위 경보는  11회 반복 / 표출 시간 20분 


# 송출대상 재난코드 정의 파일
real_warnning_json_path: "http://science.kbs.co.kr/EDBS/edbs_code.json"

# 티커 참조 이미지 경로 : ticker_ref.  png원본, jpg는 캡쳐화면에서 뽑은 거.
ticker_reference: "./resources/ticker_org.png"

# 자막인식을 위한 Tesseract 프로그램 설치 경로
pytesseract_path: "C:/Program Files/Tesseract-OCR/tesseract.exe"  
# 티커 임시저장 경로
ticker_temp_image: "./resources/ticker_temp_image.jpg"
#자막 임시저장 경로
subtitle_temp_image: "./resources/subtitle_temp_image.jpg"
# LOG 파일 경로 *** 이 코드는 소스코드에 하드코딩되어 있음
log_path : "./resources/"
log_filename : 'disaster_log.log'
max_log_size : 1024  # kbyter

#재난티커 나오고 자막 캡쳐할 지연 시간
delay_subtitle: 8
#4단계 재난경보에서 CAP 수신후 화면 캡쳐까지 지연시간(초)
delay_Emergency_subtitle: 15
#긴급 재난 송출 시간(초) : 긴급재난은 7분간 송출된다는 전제함. 
emergency_tx_duration : 420
#재난티커가 사라지고 일정 시간 지나면 재난 메시지 큐를 초기화하게됨
ticker_off_init_duration: 45

#ticker_threshlod 
#20250401 유사도 비교 방식을 변경하면서 디폴트 값 수정함. 
ticker_True_threshold : 0.85
ticker_False_threshold : 0.85

# save_video 값이 True 인경우 video_save_path경로에 mp4비디오를 저장하게됨
save_video: False
video_save_path: "./resources/"

# 재난티커 이미지 위치 (x1, y1, x2, y2)
position_subtitle:
  - [0, 492]    # 좌상단
  - [780, 519]  # 우하단
position_emergency_subtitle:
  - [0, 250]    # 좌상단
  - [960, 520]  # 우하단

position_tick:
# 자막 위치 (x1, y1, x2, y2)
  - [781, 492]  # 좌상단
  - [960, 519]  # 우하단


# OpenAI API 키는 환경변수 OPENAI_API_KEY로 설정하세요.
# API 키는 절대 소스코드에 포함하지 마세요.

#프로그램 실행 명령어 
# python .\DisasterTV_AI.py
#  'd:\Users\KBS\miniconda3\envs\disaster\python.exe' 'c:\Users\KBS\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '11279' '--' 'd:\Pyhome\Disaster\Watcher\DisasterTV_AI.py'